### ISSUE TITLE
Definition of image ids for YFCC100M

### ISSUE THREAD

**Issue by JackInTaiwan** [google-research/noisy-fewshot-learning#1]
Hi there,

Recently, I have a great interest in this work aiming at addressing such a few-shot-like task with additional noisy data.
Nevertheless, some problems about data pre-processing raised. As stated in this repository `e.g. 13, 795 means that the 13th image of the YFCC100M dataset was used for the 795th class of Shot ImageNet Benchmark.`, I do not really understand what "13th" image exactly means. As I know, all images in YFCC100M are now stored in AWS s3 in a hierarchical manner, and there is no "image id" or something like that indicating "n-th" image.
May you have an instrument or clue to guide one to derive the "image id" for YFCC100M?

**Comment by ahmetius** [comment]
Hi,

First of all, thank you for your interest in work.

YFCC100M originally contained a "dataset file" of 100M lines (named yfcc100m_dataset), where each line contained the following information for the corresponding image:

 * Line number
 * Photo/video identifier
 * Photo/video hash
 * User NSID
 * User nickname
 * Date taken
 * Date uploaded
 * Capture device
 * Title
 * Description
 * User tags (comma-separated)
 * Machine tags (comma-separated)
 * Longitude
 * Latitude
 * Accuracy of the longitude and latitude coordinates (1=world level accuracy, ..., 16=street level accuracy)
 * Photo/video page URL
 * Photo/video download URL
 * License name
 * License URL
 * Photo/video server identifier
 * Photo/video farm identifier
 * Photo/video secret
 * Photo/video secret original
 * Extension of the original photo
 * Photos/video marker (0 = photo, 1 = video)

The indices that we provided correspond to the the lines of that file, i.e. 13 means it's the image described in the 13th line of that file.

I'm not familiar with how the dataset is hosted nowadays. Could you check to see if such file still exists?

**Comment by JackInTaiwan** [comment]
Hi, @ahmetius 

My apologies for the late response.
Following your guidance, I used the dataset consisting of 100M lines to figure out the indices of interest.

I did appreciate your detailed reply!

**Comment by g-luo** [comment]
@JackInTaiwan where were you able to find the metadata for YFCC100M / the file called yfcc100m_dataset?

**Comment by g-luo** [comment]
Never mind; found at: https://multimedia-commons.s3-us-west-2.amazonaws.com/tools/etc/yfcc100m_dataset.sql

**Comment by rohit-gupta** [comment]
@g-luo did you figure out how to get the md5 hash from this file ?

When I load it up, it only has these columns 

Table: yfcc100m_dataset
  - photoid (type: INTEGER)
  - uid (type: TEXT)
  - unickname (type: TEXT)
  - datetaken (type: TEXT)
  - dateuploaded (type: TEXT)
  - capturedevice (type: TEXT)
  - title (type: TEXT)
  - description (type: TEXT)
  - usertags (type: TEXT)
  - machinetags (type: TEXT)
  - longitude (type: TEXT)
  - latitude (type: TEXT)
  - accuracy (type: INTEGER)
  - pageurl (type: TEXT)
  - downloadurl (type: TEXT)
  - licensename (type: TEXT)
  - licenseurl (type: TEXT)
  - serverid (type: INTEGER)
  - farmid (type: INTEGER)
  - secret (type: TEXT)
  - secretoriginal (type: TEXT)
  - ext (type: TEXT)
  - marker (type: INTEGER)
